services:
  web:
    image: nginx:latest
    container_name: dockng1
    volumes:
    - ./app:/usr/share/nginx/html/ # mount app directory to container's http directory
    - ./default.conf:/etc/nginx/conf.d/default.conf # mounting custom config to containers config
    # - ./certs:/etc/nginx/certs # for https certificates
    ports:
    - "80:80"
    # environment:
    # - NGINX_HOST=foobar.com
    # - NGINX_PORT=80